### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by xfq** [anssiko/das-wg#1]
I think the font size is too small to be legible. I'm aware that it's inherited from the Modernist theme, but I do hope we can increase the font size a bit, or at least remove `user-scalable=no` from the viewport meta tag.

Also, in the Roadmap page, I think the color contrast of the Recommendation column under the "Completed" subheader is not enough.

**Comment by anssiko** [comment]
Migrated to https://github.com/w3c/devicesensors-wg/issues/15
